### ISSUE TITLE
Request for 'Move' feature with two options

### ISSUE THREAD

**Issue by ghost** [trandaison/vscode-duplicate#1]
### Feature Description
I recommend adding a 'move' option. This would allow users to:

1. Just move a file or folder to specific locations within or outside the project directory.
2. Choose to duplicate a file or folder (without the "copy" suffix) and move it within or outside the project directory.

- Overwrite option if that file or folder already exists (Applicable for these two options)
  ```
  A file with this name already exists. Overwrite?
  Yes
  No
  ```

---

It's a big request, but please consider it if you have some free time.

- Currently, we can duplicate and move files or folders within the project directory by typing like `folder/Newfile` or `folder/folder/NewFolder` but typing out folder names can be quite tiring.

- Adding autocompletion of folders would be a valuable enhancement.

**Comment by ghost** [comment]
Forgot to mention the 'overwrite' option. Please take a look at my latest edit.

**Comment by trandaison** [comment]
@backermanbd Sounds good. But for me, drag and drop a file/folder to move to a new location should be more efficient 🤔

**Comment by ghost** [comment]
Many folks like to duplicate a folder and send it to another directory simultaneously. That's what I was talking about.

**Comment by trandaison** [comment]
@backermanbd Please update the extension to the new version `v0.0.3` 🎉

**Comment by ghost** [comment]
Mindblowing as expected

**Comment by ghost** [comment]
@trandaison Check your mail. Sent you something ;)
